### ISSUE TITLE
Add support for model inheritance in admin module

### ISSUE THREAD

**Issue by jensljungblad** [varvet/godmin#122]
So that you can do

```ruby
module Admin
  class Article < ::Article
    def admin_specific_method; end
  end
end
```

And have that class automatically picked up and used. Currently it seems the `ResourceService#resource_class_name` method needs to be fixed to support this.

**Comment by jensljungblad** [comment]
@mwq if you find other stuff that breaks, post it here!

**Comment by anderscarling** [comment]
I  do this by overriding `ResourceService#resource_class` and providing a `Admin::ModelName.policy_class`.

**Comment by jensljungblad** [comment]
Closing
