### ISSUE TITLE
Batch actions break when navigating between scopes

### ISSUE THREAD

**Issue by jensljungblad** [varvet/godmin#129]

**Comment by jensljungblad** [comment]
This is caused when turbolinks is enabled, which is it is if you're installing Godmin into a regular app. How should we deal with this?

1. Remove turbolinks from the javascript manifest when installing godmin
2. Enable turbolinks support in godmin

**Comment by Linuus** [comment]
Of course Turbolinks screws things up :disappointed:

I say remove Turbolinks when installing.

**Comment by jensljungblad** [comment]
Yeah perhaps for now. It would probably be easy to enable it though, we're not really doing anything fancy in the javascripts. But not super crucial I guess.
