### ISSUE TITLE
Override datepicker locale

### ISSUE THREAD

**Issue by Linuus** [varvet/godmin#132]
This commit: https://github.com/varvet/godmin/commit/3ca5e0774bb198405b63bf8573b5abb652eb538d
Which defaults the datepicker locale to en-GB makes it impossible to override the used locale.

It does not care if I add `moment/sv` in my application.js.

I've seen this issue on multiple applications.

I guess the issue is that we need to require the moment/locale file before the datepicker (which is required by godmin). So, if I write:
```
//= require moment
//= require moment/sv
//= require godmin
```
The locale is overridden when godmin requires `moment/en-gb` later. So... we probably need to remove the default? :-1: 

Not sure what to do about the date parsing though :(

**Comment by jensljungblad** [comment]
What if you require moment/sv after godmin?

**Comment by Linuus** [comment]
It doesn't work because we need to require it before the datepicker and
godmin requires that.

ons 7 okt. 2015 kl. 22:08 skrev Jens Ljungblad <notifications@github.com>:
