### ISSUE TITLE
Engine: Devise/AdminUser class conflict

### ISSUE THREAD

**Issue by benjamin-thomas** [varvet/godmin#145]
First congratulations for this gem. It's a joy to use and I love the design - awesome!!

The plugin generator `godmin:authentication` spits out this method:

```ruby
def admin_user_class
    AdminUser
end
```

If one already has a class defined in the main app, the wrong class will be returned here:
https://github.com/varvet/godmin/blob/e0d7fbe81fa225f9f45c7917b461c41fd8f57e23/lib/godmin/authentication/sessions_controller.rb#L11

Thus the namespacing should rather be explicit.

```ruby
module Admin2
  class ApplicationController < ActionController::Base
    include Godmin::ApplicationController
    include Godmin::Authentication

    def admin_user_class
      Admin2::AdminUser
    end
  end
end
```

**Comment by jensljungblad** [comment]
Thanks! Glad to hear you like it. 

Agreed, this is a bug. The generator should be fixed so that it prefixes the class with the namespace if present. Shouldn't be hard to fix. If you want to send a PR, you're welcome to assign yourself to this issue.

**Comment by benjamin-thomas** [comment]
Sure I'll have a look.

I'm not familiar with the rails generators API. Anything I need to know apart from what's available in the [rails guide?](http://guides.rubyonrails.org/generators.html)

**Comment by jensljungblad** [comment]
Nah, that should be enough. This is the file you want to change: https://github.com/varvet/godmin/blob/master/lib/generators/godmin/authentication/authentication_generator.rb#L36

And these are our own base classes:
https://github.com/varvet/godmin/blob/master/lib/godmin/generators/base.rb
https://github.com/varvet/godmin/blob/master/lib/godmin/generators/named_base.rb

You want to look at the namespace helpers, either `namespace` which returns a constantized module, or `namespaced_path` which returns an underscored array.

**Comment by jensljungblad** [comment]
Also, sorry to say we don't have any tests for the generators, we're gonna look into that eventually. It's a bit of a hassle now to test that things work both for engine installs and non-engine installs.

**Comment by benjamin-thomas** [comment]
Got you.

Could you review my proposed change? I manually tested the generators with a standalone app and an engine.

**Comment by jensljungblad** [comment]
Looks good to me, you wanna open a PR?

**Comment by benjamin-thomas** [comment]
Done, thanks for the heads up!
