### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by jcampbell05** [varvet/godmin#147]
Do I need to use ActiveRecords for this or is it agnostic ?

**Comment by jensljungblad** [comment]
Yeah it's AR only for the time being. We haven't personally had any other use cases yet. What libs would you like supported?

**Comment by jcampbell05** [comment]
We are working with Firebase but I realise this may not be easy to do, so a NO-SQL Layer may be easier.

**Comment by jensljungblad** [comment]
NoSQL would be cool, but we don't have any such projects currently. If someone wants to look into it feel free! 

I think it could be doable, but perhaps all features would not be available. I'm not sure how good NoSQL gems integrate with forms and associations for instance.
