### ISSUE TITLE
Add support for order_by method override

### ISSUE THREAD

**Issue by anderscarling** [varvet/godmin#152]
As of 1.0, if I add a field backed by a calculated property (i.e. an ordinary method) it's not possible to sort the index view based on that field. That's of course understandable as the only way to automatically do that would be to load the full data set into memory, sort and then discard all the data not needed due to pagination.

However I suggest allowing `ResourceService` implementing an order_by method override, as in many cases it would be quite easy to drop in ordering logic. It really improves UX of the resulting admin interface as well.

Suggested API:

```ruby
def order_by_username(resources, asc)
  resources.joins(:user).order("users.name #{asc ? "ASC" : "DESC"}")
end
```

Would anyone else find this useful? And please someone - suggest a nicer way to do that second parameter. :)

**Comment by jensljungblad** [comment]
I like it.

Perhaps pass it a direction parameter instead?

**Comment by anderscarling** [comment]
Maybe passing `:asc` or `:desc` as a `direction` param?

That way you could just to_s the param into sql or do whatever you want with it in code.

**Comment by jensljungblad** [comment]
Yeah exactly

**Comment by benjamin-thomas** [comment]
This would allow one to sort the `Author` column [demoed in the sandbox](http://godmin-sandbox.herokuapp.com/) right? (Defined [here](https://github.com/varvet/godmin-sandbox/blob/master/app/services/article_service.rb#L4))

Sounds great! Although I'd avoid string interpolation, just in case.

**Comment by anderscarling** [comment]
@benjamin-thomas That's the idea.
I agree that string interpolation feels scary though, but in that spirit I did some googling.

ActiveRecord actually provides a way to reverse a predefined sort order, so if we only require the `order_by_FIELDNAME` method to implement forward sort. Then could just flip the resulting sort with [`ActiveRecord::QueryMethods#reverse_order](http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-reverse_order)

Then the API would just be:

```ruby
def order_by_username(resources)
  resources.joins(:author).order("users.name")
end
```

**Comment by benjamin-thomas** [comment]
Yeah the problem with `reverse_order` is that it can do too much.

For instance let's say I want to (always) list the latest articles, but prioritizing the early joined authors:

```ruby
def order_by_author_joined_on(resources)
    # here resource = Article.order(published_on: :desc)
    resources.joins(:author).order('authors.joined_on ASC')
end
```

Calling `reverse_order` on that relation object is going to flip the order of **all** the columns (not expected).

What I meant earlier is that the string interpolation make me feel uneasy because I can't see the `direction` parameter being sanitized.

If there's an API change later on I could (theoretically) open myself to sql injection without realizing.

I'd rather not worry about that, and from that point of view, I feel the boolean parameter is probably the best option.

**Comment by jensljungblad** [comment]
@anderscarling if you feel like giving this a go, feel free to open a PR!

**Comment by anderscarling** [comment]
@jensljungblad I don't have time to do it right now, but I'll try to get it done during the holidays.

I'll give notice here before I start building, so if anyone else want's it faster than my time allows, feel free to go ahead (but drop a note here before you start as to make sure we don't do the work twice).

**Comment by jensljungblad** [comment]
Sounds good to me :+1:

**Comment by Linuus** [comment]
I'll take a look at this :fist:
