### ISSUE TITLE
Opinions about ajax in godmin?

### ISSUE THREAD

**Issue by anderscarling** [varvet/godmin#154]
I have a case where ajax powered batch actions (and resource actions, #153) would be really nice to have, as the data set presented is quite slow and obviously there will be cases where data just can't be cached or pre-calculated.

What is the opinion about ajax in godmin, is there as philosophical reason it's not there or would it be a welcome addition?

I think it should be quite straightforward to add ajax based actions. (Adding a new _row partial would make for easy rendering of updated rows and the only special cases I can think of is "row was deleted during action, mark as deleted in ui" and "error occurred, show generic error message".)

**Comment by jensljungblad** [comment]
We haven't really given it much thought. I say it's worth to discuss it. This one is perhaps related as well: https://github.com/varvet/godmin/issues/165

One thing with batch actions is that they can have redirects. We often redirect to a different scope after a batch action for instance. That's a bit tricky with ajax.

**Comment by jensljungblad** [comment]
@johanhalse you wanna be part of discussing this?

**Comment by jensljungblad** [comment]
I've got nothing against adding ajax stuff in principal. But I think we need to look at this for a particular feature. Feel free to open PR:s!
