### ISSUE TITLE
Access url params at the service object level ?

### ISSUE THREAD

**Issue by benjamin-thomas** [varvet/godmin#156]
I'm not sure if this is a great idea, but I'm used to override a page's behavior by tweaking the url.

For instance let' say I have a `per_page` method defined in a service class:

```ruby
def per_page
  if scope == 'requires_action
    10
  else
    super
  end
end
``` 

I'd like to optionally override this behavior, via the url:

```ruby
def per_page
  return params[:per_page].to_i if params[:per_page]

  if scope == 'requires_action
    10
  else
    super
  end
end
``` 

Right now this seems impossible, the params hash get's left behind at the service object initialization [right here](https://github.com/varvet/godmin/blob/6e9a22517af06d36596deb2051f987fd3ed77858/lib/godmin/resources/resource_controller.rb#L103).

Would it be reasonable to optionally let through certain url params defined on the service class for instance:

```ruby
class ArticleService
  required_params :per_page, url_param1, url_param2
end
```

Any thoughts?

**Comment by jensljungblad** [comment]
We've had some issues with this as well, when we needed to access some kind of special param in a service object method but couldn't access it. We've debated before just passing the params to the service object at initialization but I guess we felt we broke encapsulation a bit. But I agree that it's a problem.

We've solved it before by doing something like this in the controller:

```ruby
def resource_service
  resource_service_class.new(admin_user: admin_user, some_param: params[:some_param])
end
```

@Linuus you have any thoughts on this?

**Comment by benjamin-thomas** [comment]
Thanks for the workaround.

Have you thought about making it the service's responsibility to declare it's dependencies at initialization? That way you would give full control back to the programmer?

Something roughly like this:

```ruby
module ResourceController
  def resource_service
    resource_service_class.new(self)
  end
end

module Admin
  class ArticleService
    def initialize(controller)
        super # optionally sets the admin user
        @per_page = controller.params[:per_page]
        @referrer = controller.request.referrer
        @remote_ip = controller.request.remote_ip
        # etc.
    end
  end
end
```

**Comment by benjamin-thomas** [comment]
Actually scratch that, I was a bit worried about having to override the admin_user logic, but this seems perfectly reasonable to me:

```ruby

    def resource_service
      service = super
      service.options[:per_page] = params[:per_page]
      service
    end

    # or
    def resource_service
      super.tap do |service|
        service.options[:per_page] = params[:per_page]
        # etc.
      end
    end
```

What do you think?

**Comment by jensljungblad** [comment]
Yeah that's better than what I wrote. Perhaps we should just add a note to the README about this.

**Comment by jensljungblad** [comment]
Added a note in the readme about this.
