### ISSUE TITLE
Multiselect filter sends invalid array item

### ISSUE THREAD

**Issue by benjamin-thomas** [varvet/godmin#161]
If I select 2 items with ids 1 and 2 in my list

```ruby
def filter_column_multi(relation, values)
    # values here will be == ['', '1', '2']
    rel.where(col_id: values)
end
```

Not a big deal but the query above will be translated to:

```sql
SELECT * FROM my_table WHERE col_id IN (NULL, 1, 2);
```

The NULL value will in fact be ignored, but it should really be filtered prior to being received by the filter method.

**Comment by jensljungblad** [comment]
Hm yeah I remember this. We've done something like this before:

```ruby
def filter_tags(resources, value)
  resources.tagged_with(value.reject(&:blank?))
end
```

Not sure why we didn't filter it before passing the value to the filter method. @Linuus you remember?

**Comment by Linuus** [comment]
I don't know if we should filter blank items by default. Maybe it is actually useful in some case to have blank items? Or do I misunderstand?

We should check why it returns an empty item at all though.

**Comment by benjamin-thomas** [comment]
Right, I didn't realize this was a rails default.

A solution could be to accept an html_options hash to mirror the rails API?

Or just document the fact that this is the default/intended behavior, because selecting 2 items and having 3 fed into the method is counter intuitive IMO.

**Comment by Linuus** [comment]
@benjamin-thomas Do you actually get the empty item in your `filter_*` method?

It think it should be filtered out here:
https://github.com/varvet/godmin/blob/master/lib/godmin/resources/resource_service/filters.rb#L22-L25

It would be better to fix the root cause though and remove that code :)

**Comment by benjamin-thomas** [comment]
@Linuus yes that's right, a "bogus" empty item is always fed to the filter_* methods right now, once  one or more items have been selected.
