### ISSUE TITLE
filter with checkboxes seems not implemented

### ISSUE THREAD

**Issue by benjamin-thomas** [varvet/godmin#162]
Mentioned in the README: https://github.com/varvet/godmin#filters

    There are four types of filters: string, select, multiselect and checkboxes, specified using the as parameter.

It seems like this feature is not implemented?

https://github.com/varvet/godmin/blob/af140c79413a6f02ac634aa1864000174d58b839/lib/godmin/helpers/filters.rb#L14

**Comment by jensljungblad** [comment]
Correct, we had it once but removed it because we never used it. I'll fix it in the README.
