### ISSUE TITLE
Ajax filters / linked filters

### ISSUE THREAD

**Issue by benjamin-thomas** [varvet/godmin#165]
It'd be nice to have ajax filters (select tags) for cases where the dataset is large.

This is roughly what I have in mind:
https://github.com/varvet/godmin/compare/af140c79413a6f02ac634aa1864000174d58b839...benjamin-thomas:ajax-filters-spike

It's not even half baked, although the ajax query (hard coded) did work.

 I don't really understand the existing js structure (`initializeState` and `initializeEvents`).

Would it be ok to rework that part?

I'll also have to dig into the `selectize` API.

I'd also like to be able to link 2 filters together, like in [the selectize doc](https://brianreavis.github.io/selectize.js) (City / State Selection).

Any thoughts?

**Comment by jensljungblad** [comment]
Closing this for now. We'll probably think more about this stuff in a future version though.

**Comment by benjamin-thomas** [comment]
Hi @jensljungblad 

I've been exploring this project this week: http://projects.sergiodinislopes.pt/flexdatalist/

There's a `chainedRelatives` feature as well as very easy ajax calls right out of the box.

Although there's a slight overlap in functionality with selectize, I feel it may make a nice addition to godmin in the future.

Food for thought...

**Comment by jensljungblad** [comment]
Looks interesting! I'll def check it out.
