### ISSUE TITLE
Enable setting the name of the admin area to be shown in the top left, instead of Godmin

### ISSUE THREAD

**Issue by johanhalse** [varvet/godmin#17]

**Comment by jensljungblad** [comment]
Perhaps this should be done with a translation string? @Linuus

**Comment by Linuus** [comment]
@jensljungblad Well, one downside is that you must specify it for all your languages if you do it that way.

**Comment by jensljungblad** [comment]
True. Is that a big problem you think? Guess it depends on how many languages you're using. My guess would be it's usually just one. 

The alternatives are, I guess, either a config setting or a view partial.

**Comment by Linuus** [comment]
Perhaps we can use translation though. Isn't it possible to fall back to english if translation is missing? If so, it would be possible to specify a different name for different languages but have a fallback if you don't want to. If you only have one language you can just specify the name there. Right?

**Comment by jensljungblad** [comment]
We could try! Should probably also print the title in the title bar of the browser.
