### ISSUE TITLE
Authentication with Devise failed

### ISSUE THREAD

**Issue by raecoo** [varvet/godmin#171]
I’ve followed the __Shared Authentication__ section to integrate with __Devise__ then encountered these errors:

```ruby
undefined method `authenticate_user!' 
```
When I change the method `authenticate_admin_user` like

```ruby
    def authenticate_admin_user
      false
    end
```
to skip this error, and then another error occurs.

```ruby
  # wrong number of arguments (0 for 1)
  # devise (3.5.2) lib/devise/models/database_authenticatable.rb:143:in `password_digest'
  def password_digest(password)
    Devise::Encryptor.digest(self.class, password)
  end
```
Do I missing something?

**Comment by raecoo** [comment]
Is there a full example of authentication integration with devise?

**Comment by raecoo** [comment]
@jensljungblad  Is there a full example of authentication integration with devise?

**Comment by jensljungblad** [comment]
Weird. The `authenticate_user!` method is added to `ActionController::Base` by Devise. So it should be defined. Try running `included_modules` on your Godmin controller and see if its being included.

```ruby
Admin::ApplicationController.included_modules
```

You should see `Devise::Controllers::Helpers` etc.

**Comment by jensljungblad** [comment]
Sorry, no complete examples online, but we have projects where we do this. They're running Devise 3.4.1. What version are you on?

**Comment by raecoo** [comment]
@jensljungblad Devise 3.5.2

**Comment by raecoo** [comment]
```ruby
[1] pry(main)> Admin::ApplicationController.included_modules
=> [Godmin::Authentication,
 Godmin::Helpers::Translations,
 Godmin::ApplicationController,
 #<Module:0x007fb271bdaa08>,
 #<Module:0x007fb273249320>,
 #<Module:0x007fb273249348>,
 Devise::Controllers::UrlHelpers,
 Devise::Controllers::Helpers,
 Devise::Controllers::StoreLocation,
 Devise::Controllers::SignInOut,
```

**Comment by raecoo** [comment]
@jensljungblad The problem has been resolved. I will add a guide [How to integration access authentication with Devise](https://github.com/varvet/godmin/wiki/How-to-integration-access-authentication-with-Devise) in Wiki.

**Comment by jensljungblad** [comment]
Hey. Looked at what you wrote and all of that should definitely not be necessary. Seems like something is wrong. I'll post our setup when I have some time, but basically it should be enough to do what is written in the readme.

**Comment by raecoo** [comment]
something is wrong?
Jens Ljungblad <notifications@github.com>于2015年12月17日 周四上午5:56写道：

> Hey. Looked at what you wrote and all of that should definitely not be
> necessary. Seems like something is wrong. I'll post our setup when I have
> some time, but basically it should be enough to do what is written in the
> readme.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/varvet/godmin/issues/171#issuecomment-165256611>.
>
-- 
Best

Raecoo Cao
--
Send from my phone

**Comment by raecoo** [comment]
I've removed the wiki page. :)
