### ISSUE TITLE
Support active_resource

### ISSUE THREAD

**Issue by PuGGee** [varvet/godmin#173]
Are there any plans for godmin to support active_resource in the future? Currently, it seems that a lot of hacks are required if you want to use both at the same time.

**Comment by Linuus** [comment]
I've never used [active_resource](https://github.com/rails/activeresource). What kind of hacks do you need today? If it has the same API as ActiveRecord it should work pretty well.

**Comment by Linuus** [comment]
@PuGGee I had a quick look at this and there are quite a lot of stuff breaking at the moment (pagination etc). I don't think we will build in compatibility for this unless we need it ourselves. However, if someone wants to draw up a PR for this we are happy to take a look at it. :)

Do you have any other input here @jensljungblad?
