### ISSUE TITLE
Switch to Bootstrap 4

### ISSUE THREAD

**Issue by adimasuhid** [varvet/godmin#198]

**Comment by jensljungblad** [comment]
Well, Bootstrap 4 is still in alpha, so we're not gonna work further on this until at least beta. But there is an early PR if you're interested: #138 

Closing for now

**Comment by jensljungblad** [comment]
Or I guess we can leave it open, since we intend to do this eventually...

**Comment by jensljungblad** [comment]
Closing in favour of https://github.com/varvet/godmin/issues/213
