### ISSUE TITLE
Template problems with Rails 5

### ISSUE THREAD

**Issue by jensljungblad** [varvet/godmin#204]
Seems like something changed in Rails 5 that creates new Ruby processes for every generate command. When running the template things hang after a while, probably because processes compete with each other or something.

**Comment by Linuus** [comment]
I added an issue with a minimal test case at the rails repo for this.

https://github.com/rails/rails/issues/27178

**Comment by Linuus** [comment]
Aaand, it's of course related to your old issue @jensljungblad 

https://github.com/rails/rails/issues/21700

**Comment by jensljungblad** [comment]
This can be worked around by passing `--skip-spring` as an option.

**Comment by jensljungblad** [comment]
This is a Rails issue. Closing.
