### ISSUE TITLE
Not authenticated alert not localized, and also annoying

### ISSUE THREAD

**Issue by jensljungblad** [varvet/godmin#206]
This thing is not localized:

```ruby
def authenticate_admin_user
  unless admin_user_signed_in? || controller_name == "sessions"
    redirect_to new_session_path, alert: "Authentication needed"
  end
end
```

But also, I find it annoying. It's always shown basically, because you never go directly to the login page. Rather you try accessing `/admin` or something, which then triggers the above code which redirects to the login page with a message. My suggestion would be to just skip the message entirely. It's kinda obvious you need to login when you are redirected to a login page.

**Comment by Linuus** [comment]
That code doesn't redirect you, does it? It just shows the text. In my opinion it's a good enough default. If a user wants something else to happen they can create their own `rescue_from`, right?

**Comment by jensljungblad** [comment]
Yeah sorry no redirect. But couldn't we just skip the text?

**Comment by Linuus** [comment]
But this text is not shown on the login page, ever :)

**Comment by jensljungblad** [comment]
Oops, wrong code. Fixed.

**Comment by Linuus** [comment]
I think you're talking about the authentication stuff.

https://github.com/varvet/godmin/blob/8bdd87cfb100927c16863baae53690c589b281cd/lib/godmin/authentication.rb#L15-L19

I'm fine with removing that text.
