### ISSUE TITLE
Templates should follow routes file

### ISSUE THREAD

**Issue by benjamin-thomas** [varvet/godmin#215]
Suppose I declare a resource as such in my routes file:

    resources :latest_posts, only: [:index]

Then those 2 partials cause an exception:

- app/views/godmin/resource/_button_actions.html.erb
- app/views/godmin/resource/columns/_actions.html.erb

Internally, `link_to` calls `url_for` and generates a route that does not exist for new, edit, show, and triggers the exception.

For now, I've worked around this by overriding the partials, but It'd be nice if godmin would follow the routes file by default.

What are your thoughts on this ?

I couldn't find a way to check if a route name is implemented from the view.

Another approach is to implement a policy object but that feels heavy handed IMO.

**Comment by jensljungblad** [comment]
Hm, that might be doable. Never needed it but not opposed to it if it could be done in a nice way. There's `Rails.application.routes.url_helpers.respond_to?(:some_path)` which might work.

**Comment by benjamin-thomas** [comment]
I can't see a clean way to do it.

The main problem starts from `link_to` calling `url_for` [which is itself super complex](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/url_for.rb#L150).

Digging into it's internal to find a way to generate a method name's symbol was fruitless for me.

It seems there's no good way to probe for a route method name for `Rails.application.routes.url_helpers.respond_to?`, without generating more exceptions.

Even then delete routes would be problematic because the `method` parameter is specified to `link_to`.

So `link_to` would have to be overridden which is not great.

Maybe a simpler approach would be to conditionally implement the CRUD methods in `Godmin::Resources::ResourceController`, but only if defined in the routes file, which would require some kind of parsing.

Not sure if it's doable though.

Then the view code could be:

```ruby
if controller.respond_to?(:edit)
  link_to([:edit, resource])
end
``` 

Any thoughts ?

**Comment by benjamin-thomas** [comment]
So I kept digging and this seems to work (ok to copy-paste in the rails console)

```ruby
klass = Post
mb = ActionDispatch::Routing::PolymorphicRoutes::HelperMethodBuilder.get(nil, :path)

index_path, _args = mb.handle_list([klass])
new_path, _args = mb.handle_list([:new, klass.model_name.singular_route_key])
edit_path, _args = mb.handle_list([:edit, klass.take])
show_path, _args =mb.handle_list([klass.take])

{ index: index_path, new: new_path, edit: edit_path, show: show_path }.map do |action, path|
  { action => Rails.application.routes.url_helpers.respond_to?(path) }
end
```

That would have to be wrapped in a helper method, the delete routes would still be a problem though.
