### ISSUE TITLE
Is it possible to use postgres instead of sqlite3 in engine setup?

### ISSUE THREAD

**Issue by rubendinho** [varvet/godmin#234]
I am setting up Godmin using the engine route but am getting the below error running `admin/bin/rails bundle install`

```
Could not find gem 'sqlite3' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems. 
```

My project uses postgres and I'd like to avoid bundling sqlite3 if possible.

**Comment by jensljungblad** [comment]
That's weird. It's probably referring to the development dependency in your `admin/admin.gemspec` which reads `s.add_development_dependency "sqlite3"`. It's something Rails adds and uses for the dummy app that gets created along with your engine, to be used for tests. 

The error says that the gem couldn't be found, which is weird. I assume you still have `source 'https://rubygems.org'` in your Gemfile? Perhaps the site was down for a bit or something.

You can always remove the development dependency as well, if you're not gonna use the dummy app.

**Comment by rubendinho** [comment]
I fall in the category of people discussed #227 who are still getting their bearings around non-Rails uses of Bundler.  I ended up having to install the gem manually to bypass the warning. Thanks.
