### ISSUE TITLE
Drop support for Rails 4

### ISSUE THREAD

**Issue by jensljungblad** [varvet/godmin#240]
Drop support for Rails 4 going forward.

**Comment by Linuus** [comment]
Why?

**Comment by jensljungblad** [comment]
Mainly I was thinking so we can use Rails 5 features such as yarn and webpack. Also take advantage of Ruby 2.2.2. And also because this is probably the only opportunity we will have to do it :) I doubt we will finish 2.0 anytime soon as well, so apps have plenty of time to upgrade, if they even want to upgrade to the new godmin.
