### ISSUE TITLE
Inject default filter values

### ISSUE THREAD

**Issue by benjamin-thomas** [varvet/godmin#246]
Hi, I'd like to document this need, in the `README` if that's ok with you?

It seems this would be the best approach, what do you think?

```ruby
def resources(params)
  params[:filter] ||= ActionController::Parameters.new # when no active filters yet
  params[:filter][:author_name] || params[:filter][:author_name] = 'John Doe'

  super(params)
end
```

With one possible downside being the URL would not reflect the filters state. In that use case a redirect from `index` would be more appropriate.

**Comment by jensljungblad** [comment]
Interesting.. Perhaps rather add a `default` option to the `filter` DSL? And grab the default as the filter value unless one is set.

**Comment by benjamin-thomas** [comment]
Yes adding on option to the DSL would make things simpler and more readable. I'm not sure if that's enough of a common use case though?

I'd like to work on this if you feel the DSL could be extended?

As a first step, I'd like to contribute setting up a docker based development environment.
What do you think?

**Comment by jensljungblad** [comment]
Yeah now that I think about it, perhaps it is better to implement this with a redirect? https://api.rubyonrails.org/classes/ActionDispatch/Routing/Redirection.html. That way the URL will, as you say, reflect the filter state. And yeah it doesn't seem like a common use case so perhaps extending the DSL doesn't make sense.

**Comment by benjamin-thomas** [comment]
I've submitted a wiki page: https://github.com/varvet/godmin/wiki/Tips-and-tricks-(hacky)

It didn't come to me straight away that those kind of tricks could be used with `godmin`, so I can imagine this being useful to someone else.

Before considering framework design/requests. I could probably add a few more ideas. What do you think?

**Comment by jensljungblad** [comment]
Haha, that's a cool filter :D Never even entered my mind that was possible.. Good job :)

Yeah, a Wiki page seems like a nice idea.
