### ISSUE TITLE
Support Rails 6

### ISSUE THREAD

**Issue by rubendinho** [varvet/godmin#247]
Are there plans to add support for Rails 6?

**Comment by jensljungblad** [comment]
You can clone godmin, then point to that directory in your `Gemfile`:

```
gem "godmin", path: "path/to/cloned/godmin"
```

Once you've done that, you can change godmin's gemspec and remove that constraint.

@Linuus I don't remember why we have this constraint in the first place.. Would it be better to just remove the upper constraint?

**Comment by Linuus** [comment]
@jensljungblad I think it's mainly a safe guard to not accidentally allow major changes.

**Comment by jensljungblad** [comment]
@rubendinho I don't think I will have time to look into this any time soon, but if you (or perhaps someone at Varvet, @johanhalse) wants to create a PR, please feel free. We also make use of https://github.com/thoughtbot/appraisal, so hopefully it's pretty easy to run the test suite for Rails 6 as well.

**Comment by johanhalse** [comment]
The test suite is easy enough to run, but something about Resolvers seems to have changed between 5.2 and 6. I've done some initial digging and the `find_templates` function in `resolver.rb` isn't being run when it's supposed to in Rails 6. Documentation there isn't great and I can't find anything in the changelog.

**Comment by Linuus** [comment]
Yeah... it looks like they’ve changed the resolver stuff a bit. Ugh... I have nightmares about these resolvers 😆

**Comment by jensljungblad** [comment]
Oh man, yeah that sucks. It was always the most annoying part of Godmin :/

**Comment by johanhalse** [comment]
Good news though, I have a PR to fix it! https://github.com/varvet/godmin/pull/248

The tests all pass but are there any obvious red flags? I haven't worked on the Godmin resolvers before so I'm not super confident.

**Comment by jensljungblad** [comment]
Hm, I don’t think so. If the tests pass and the dummy app looks okay, I’d say that’s good enough. You can run the dummy app with ‘test/dummy/bin/rails s’ if you want to poke around.

**Comment by mbajur** [comment]
Any chances to publish a new gem version with rails 6 support anytime soon? :)

**Comment by mbajur** [comment]
Ok, PR ready for a review and merge ✅

**Comment by jensljungblad** [comment]
@mbajur Merged. Feel free to try it out for a bit. If everything seems fine we can close this issue and release a new version. 

Thanks!

**Comment by mbajur** [comment]
@jensljungblad i am actually actively using my branch for last 2 days and it seems to be working perfectly fine. Consider it as a confirmation everything is good with rails 6 :)

**Comment by jensljungblad** [comment]
Looks like @johanhalse released it! 🎉
