### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by 2rba** [varvet/godmin#265]

**Comment by anderscarling** [comment]
No promises, but I'll do some work investigating this.

**Comment by brunoprietog** [comment]
Great! Do you think there is any possibility to migrate from sass-rails to dartsass-rails? There is a conflict with having sass-rails and tailwindcss-rails installed. Now using that with importmap in Rails 7.

Thanks!

**Comment by anderscarling** [comment]
@brunoprietog I'm not sure if using dartsass-rails in godmin is the right way to go (as we probably wouldn't want to force that decision to use dart sass-rails on the apps integrating godmin), but I definitely think it would be a great thing to look over the approach used for css and javascript in godmin.

I have created a separate issue - #272 - for that discussion.

**Comment by anderscarling** [comment]
Rails 7 support is in master now.

**Comment by morimorihoge** [comment]
We plan to use Godmin on our Rails 7 project.  
When will this revision be released rubygems? or is there anythng left that still needs to be addressed?
