### ISSUE TITLE
Bump the test coverage a bit

### ISSUE THREAD

**Issue by jensljungblad** [varvet/godmin#32]
There are very few tests currently, mainly because we're unsure of how to test engine things. We should investigate and get on with it.

**Comment by jensljungblad** [comment]
I was thinking about some of the stuff we currently keep in the controller layer. When using godmin you define scopes, filters and batch actions in the controller. Would it make more sense to define them on the model? Would such files be easier for people to test? It makes it possible to test scopes, filters and batch actions without running controller tests.

Something like:

```ruby
require_dependency "article"

module Admin
  class Article < ::Article
    include Godmin::Model

    scope :published -> { where(state: :published) } # using normal rails scopes

    filter :title
    filter :author

    private

    def filter_title(articles)
      articles
    end
  end
end
```

Thoughts about this @Linuus ?

**Comment by Linuus** [comment]
@jensljungblad created a separate issue about this.
https://github.com/varvet/godmin/issues/78

I will investigate :sunglasses:
