### ISSUE TITLE
Some better way of specifying navigation

### ISSUE THREAD

**Issue by johanhalse** [varvet/godmin#54]
Navigations can be kind of wordy today. Perhaps a YAML file by default would cover most cases?

**Comment by johanhalse** [comment]
What about marking the active menu item, like we do for the default nav?

**Comment by jensljungblad** [comment]
This could also potentially solve the problem of namespaced models. Currently the default navigation breaks down if there's a namespaced route for a namespaced resource. Just another reason to decouple the routing from the navigation.
