### ISSUE TITLE
Autoloading woes

### ISSUE THREAD

**Issue by jensljungblad** [varvet/godmin#60]
Some background: http://urbanautomaton.com/blog/2013/08/27/rails-autoloading-hell/

Basically, we're having some trouble with autoloading the `Admin::ApplicationController` constant when first accessing the frontend if the controller file looks like this:

```ruby
module Admin
  class ArticlesController < ApplicationController
end
```

Option 1.

```ruby
module Admin
  class ArticlesController < Admin::ApplicationController
end
```

Option 2.

Use some kind of require statement, such as `require_dependency` or something, in `admin/lib/admin.rb`

**Comment by Linuus** [comment]
Option 1 seems to be the best way IMO.

Option 2 seems not to work. `require_dependency` is not available there and using `autoload` or `require` messes up class reloading in development...

**Comment by jensljungblad** [comment]
Some problems with option 1:
- We have to rewrite all documentation
- We have to rewrite the generators
- We have to rewrite all existing apps
- There's nothing wrong with the code, only how Rails loads it

@Linuus could you try this? I still can't reproduce on my computer:

```ruby
module Admin
  class Engine < ::Rails::Engine
    isolate_namespace Admin

    config.after_initialize do
      require_dependency "admin/application_controller"
    end
  end
end
```

**Comment by Linuus** [comment]
Rewriting the things won't be that hard. Search and replace :P

This is a Rails engine so I guess we should abide by the laws of Rails...  :)

**Comment by Linuus** [comment]
Using `require_dependency "admin/application_controller"` in Engine seems to work. I don't know if it is better than just being more specific in the inheritance definition though.

**Comment by jensljungblad** [comment]
I think it's better if we can solve this in godmin rather than require everyone to follow a certain coding style. It would need to be communicated, and then people would probably still forget about it. If we can solve it out of the box while supporting all coding styles, that seems better to me.

We could inject the require_dependency line with the install generator, for instance.

**Comment by Linuus** [comment]
Inject for all controllers? I mean, the same issue will happen if you have

```
class FooController < ApplicationController
end

module Admin
  class FooController < ApplicationController
  end
end

module Admin
  class BarController < FooController
  end
end
```

BarController will inherit from the wrong class if the load order is wrong.

**Comment by jensljungblad** [comment]
https://github.com/rails/rails/blob/08754f12e65a9ec79633a605e986d0f1ffa4b251/railties/lib/rails/generators/rails/controller/templates/controller.rb
