### ISSUE TITLE
Support nested resources

### ISSUE THREAD

**Issue by Linuus** [varvet/godmin#85]
Add support for nested resources
- Set parent resource in controller.
- Access to parent resource in service and policy.
- Routes and buttons.

**Comment by benjamin-thomas** [comment]
@jensljungblad sorry about the duplicate issue.

Are you ok with suggestions? I'm going to need this so I'd rather propose some changes rather than building my own workarounds.

**Comment by jensljungblad** [comment]
That would be cool. We could probably post some of the stuff that we did in order to support this.

**Comment by jensljungblad** [comment]
Sorry, forgot about this one. This is how we currently do it:

```ruby
# routes.rb
resources :blogs do
  resources :blog_posts
end

# blog_posts_controller.rb
module Admin
  class BlogPostsController < ResourceController
    prepend_before_action :set_blog

    # So we basically just redirect here to the nested resource. Perhaps not the best solution.
    def show
      redirect_to blog_blog_posts_path(@resource)
    end

    private

    def set_blog
      @blog = Blog.find(params[:blog_id])
    end

    def resource_service
      service = super
      service.options[:blog] = @blog
      service
    end
  end
end

# blog_post_service.rb
module Admin
  class BlogPostService < ResourceService
    def resources_relation
      super.where(blog: options[:blog])
    end
  end
end
```

Then we override the breadcrumb partial for blog posts and print the `@blog` there as well.

This piece of code could come in handy as well. It basically finds the parent model from the params:

```ruby
module Nestable
  extend ActiveSupport::Concern

  included do
    private

    def find_parent_model
      candidate = params.reduce([]) do |res, (name, value)|
        if name =~ /(.+)_id$/
          res = [$1, value]
        else
          res
        end
      end
      candidate.first.classify.constantize.friendly.find(candidate.last)
    end
  end
end
```

Some things to think about:

* What should the interface look like? How do you go to the nested resource index page? If we have blogs and blog posts, how do you navigate to a blog's posts? Do you click show on the blog and see a table there? Or a link? Or an additional link for blogs next to show/edit/destroy?
* How many levels of nesting should be supported?
* How to detect if there are nested/parent resources? I'm thinking there should be some modules that you need to mix in perhaps.

**Comment by benjamin-thomas** [comment]
Thansk @jensljungblad and sorry for the late reply.

I'm very busy at the moment so I'll post my ideas in a few days.
