### ISSUE TITLE
Use .new? to authorize new button

### ISSUE THREAD

**Issue by Linuus** [varvet/godmin#89]
Here: https://github.com/varvet/godmin/blob/master/app/views/godmin/resource/_button_actions.html.erb

We wrap the button with `policy(@resources).create?`. This is a bit weird since we pass it a collection. So, you need to be aware of that `record` in the `create?` method can both be a collection AND a single record.

What do you think about using `policy(@resource_class).new?` in the `button_actions` partial instead?

**Comment by jensljungblad** [comment]
I guess you mean `policy(@resource_class).create?` right?

**Comment by Linuus** [comment]
Nope, I mean `.new?`

**Comment by jensljungblad** [comment]
Oops, got confused. Changed to `.new?`

**Comment by jensljungblad** [comment]
Though why would you be able to access new and then not create?

**Comment by Linuus** [comment]
See my edited answer above.

We do have  a `.new?` method in the policy, why is it there if we never use it? :)

**Comment by jensljungblad** [comment]
Hm yeah, but by default the godmin policy does this:

```ruby
def new?
  create?
end
```

Wouldn't that break things as well? Unless you reimplement `new?` yourself.

**Comment by Linuus** [comment]
Why would it break? We can keep the default new method to call `create?`.

**Comment by jensljungblad** [comment]
Basically, if you implement `create` in such a way that it requires an instance of a record, such as your example above, the `new?` breaks unless you implement it yourself.

Shouldn't we do something like `policy(@resource_class.new).new?`

**Comment by Linuus** [comment]
Yeah, that works too :)

**Comment by jensljungblad** [comment]
Or should we do...

```ruby
policy(@resource_service.build_resource).new?
```

Haha..

**Comment by Linuus** [comment]
Oh god... :anguished: 

Yeah maybe that's a better idea.

**Comment by jensljungblad** [comment]
I'll try it out

**Comment by jensljungblad** [comment]
Fixed in the PR
